-- Star Schema Model Design
-- Fact Tables:
-- Fact_Transactions: Links to user, team, date, and transaction dimensions.
-- Fact_Company_Spend: Links to company and date dimensions.
-- Dimension Tables:
-- Dim_User
-- Dim_Company
-- Dim_Team
-- Dim_Date
-- Dim_Deal
-- Relationships in Star Schema
-- Fact_Transactions:

-- USER_ID links to Dim_User.USER_ID
-- TEAM_ID links to Dim_Team.TEAM_ID
-- DATE_ID links to Dim_Date.DATE_ID
-- Fact_Company_Spend:

-- COMPANY_ID links to Dim_Company.COMPANY_ID
-- DATE_ID links to Dim_Date.DATE_ID


CREATE OR REPLACE TABLE INTERVIEW_DATA.DW.FACT_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(256) NOT NULL,
    USER_ID VARCHAR(256),
    TEAM_ID VARCHAR(256),
    DATE_ID DATE,
    TRANSACTION_AMOUNT NUMBER(20,10),
    QUANTITY INT,
    primary key (TRANSACTION_ID)
);

CREATE OR REPLACE TABLE INTERVIEW_DATA.DW.FACT_COMPANY_SPEND (
    COMPANY_SPEND_ID VARCHAR(256) NOT NULL,
    COMPANY_ID VARCHAR(16777216),
    DATE_ID DATE,
    TOTAL_SPEND NUMBER(30,10),
    NUM_TRANSACTIONS INT,
    primary key (COMPANY_SPEND_ID)
);


************************  Dimmensions **************************************************************

CREATE OR REPLACE TABLE INTERVIEW_DATA.DW.DIM_USER (
    USER_ID VARCHAR(256) NOT NULL,
    EMAIL VARCHAR(256),
    CLIENT_BALANCE NUMBER(30,10),
    CLIENT_LIFETIME_SPEND NUMBER(30,10),
    CREATED_AT TIMESTAMP_NTZ(9),
    REFERRAL_ID VARCHAR(256),
    SPEND_LIMIT NUMBER(38,0),
    primary key (USER_ID)
);

CREATE OR REPLACE TABLE INTERVIEW_DATA.DW.DIM_COMPANY (
    COMPANY_ID VARCHAR(16777216) NOT NULL,
    NAME VARCHAR(16777216),
    DOMAIN VARCHAR(16777216),
    CREATEDAT TIMESTAMP_NTZ(9),
    UPDATEDAT TIMESTAMP_NTZ(9),
    ARCHIVED BOOLEAN,
    CREATEDATE TIMESTAMP_NTZ(9),
    HS_LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
    HS_OBJECT_ID VARCHAR(16777216),
    primary key (COMPANY_ID)
);


CREATE OR REPLACE TABLE INTERVIEW_DATA.DW.DIM_TEAM (
    TEAM_ID VARCHAR(256) NOT NULL,
    NAME VARCHAR(256),
    OWNER_ID VARCHAR(256),
    CREATED_AT TIMESTAMP_NTZ(9),
    UPDATED_AT TIMESTAMP_NTZ(9),
    primary key (TEAM_ID)
);

CREATE OR REPLACE TABLE INTERVIEW_DATA.DW.DIM_DATE (
    DATE_ID DATE NOT NULL,
    DAY INT,
    MONTH INT,
    QUARTER INT,
    YEAR INT,
    DAY_OF_WEEK VARCHAR(10),
    primary key (DATE_ID)
);

CREATE OR REPLACE TABLE INTERVIEW_DATA.DW.DIM_DEAL (
    DEAL_ID VARCHAR(16777216) NOT NULL,
    DEAL_NAME VARCHAR(16777216),
    DEAL_STAGE VARCHAR(16777216),
    COMPANY_ID VARCHAR(16777216),
    AMOUNT FLOAT,
    CLOSEDATE TIMESTAMP_NTZ(9),
    CREATEDATE TIMESTAMP_NTZ(9),
    HS_LASTMODIFIEDDATE TIMESTAMP_NTZ(9),
    HS_OBJECT_ID VARCHAR(16777216),
    primary key (DEAL_ID)
);



************************  Data Loads **************************************************************


INSERT INTO INTERVIEW_DATA.DW.FACT_TRANSACTIONS (TRANSACTION_ID, USER_ID, TEAM_ID, DATE_ID, TRANSACTION_AMOUNT, QUANTITY)
SELECT 
    T.ID AS TRANSACTION_ID,
    T.USER_ID,
    TM.TEAM_ID,
    T.TRANSACTION_COMPLETED_AT::DATE AS DATE_ID,
    T.AMOUNT AS TRANSACTION_AMOUNT,
    1 AS QUANTITY
FROM 
    INTERVIEW_DATA.PUBLIC.TRANSACTION T
LEFT JOIN 
    INTERVIEW_DATA.PUBLIC.TEAM_MEMBERSHIP TM ON T.USER_ID = TM.MEMBER_USER_ID;


INSERT INTO INTERVIEW_DATA.DW.FACT_COMPANY_SPEND (COMPANY_SPEND_ID, COMPANY_ID, DATE_ID, TOTAL_SPEND, NUM_TRANSACTIONS)
SELECT 
    UUID_STRING() AS COMPANY_SPEND_ID,
    U.ID AS COMPANY_ID,
    T.TRANSACTION_COMPLETED_AT::DATE AS DATE_ID,
    SUM(T.AMOUNT) AS TOTAL_SPEND,
    COUNT(T.ID) AS NUM_TRANSACTIONS
FROM 
    INTERVIEW_DATA.PUBLIC.TRANSACTION T
JOIN 
    INTERVIEW_DATA.PUBLIC.USER U ON T.USER_ID = U.ID
GROUP BY 
    U.ID, T.TRANSACTION_COMPLETED_AT::DATE;


INSERT INTO INTERVIEW_DATA.DW.DIM_USER (USER_ID, EMAIL, CLIENT_BALANCE, CLIENT_LIFETIME_SPEND, CREATED_AT, REFERRAL_ID, SPEND_LIMIT)
SELECT 
    ID AS USER_ID,
    EMAIL,
    CLIENT_BALANCE,
    CLIENT_LIFETIME_SPEND,
    CREATED_AT,
    REFERRAL_ID,
    SPEND_LIMIT
FROM 
    INTERVIEW_DATA.PUBLIC.USER;



INSERT INTO INTERVIEW_DATA.DW.DIM_COMPANY (COMPANY_ID, NAME, DOMAIN, CREATEDAT, UPDATEDAT, ARCHIVED, CREATEDATE, HS_LASTMODIFIEDDATE, HS_OBJECT_ID)
SELECT 
    ID AS COMPANY_ID,
    NAME,
    DOMAIN,
    CREATEDAT,
    UPDATEDAT,
    ARCHIVED,
    CREATEDATE,
    HS_LASTMODIFIEDDATE,
    HS_OBJECT_ID
FROM 
    INTERVIEW_DATA.DW_STAGE.COMPANIES;


INSERT INTO INTERVIEW_DATA.DW.DIM_TEAM (TEAM_ID, NAME, OWNER_ID, CREATED_AT, UPDATED_AT)
SELECT 
    ID AS TEAM_ID,
    NAME,
    OWNER_ID,
    CREATED_AT,
    UPDATED_AT
FROM 
    INTERVIEW_DATA.PUBLIC.TEAM;


INSERT INTO INTERVIEW_DATA.DW.DIM_DATE (DATE_ID, DAY, MONTH, QUARTER, YEAR, DAY_OF_WEEK)
SELECT 
    DISTINCT TRANSACTION_COMPLETED_AT::DATE AS DATE_ID,
    EXTRACT(DAY FROM TRANSACTION_COMPLETED_AT) AS DAY,
    EXTRACT(MONTH FROM TRANSACTION_COMPLETED_AT) AS MONTH,
    EXTRACT(QUARTER FROM TRANSACTION_COMPLETED_AT) AS QUARTER,
    EXTRACT(YEAR FROM TRANSACTION_COMPLETED_AT) AS YEAR,
    TO_CHAR(TRANSACTION_COMPLETED_AT, 'Day') AS DAY_OF_WEEK
FROM 
    INTERVIEW_DATA.PUBLIC.TRANSACTION;


INSERT INTO INTERVIEW_DATA.DW.DIM_DEAL (DEAL_ID, DEAL_NAME, DEAL_STAGE, COMPANY_ID, AMOUNT, CLOSEDATE, CREATEDATE, HS_LASTMODIFIEDDATE, HS_OBJECT_ID)
SELECT 
    ID AS DEAL_ID,
    DEALNAME,
    DEALSTAGE,
    HS_OBJECT_ID AS COMPANY_ID,
    AMOUNT,
    CLOSEDATE,
    CREATEDATE,
    HS_LASTMODIFIEDDATE,
    HS_OBJECT_ID
FROM 
    INTERVIEW_DATA.DW_STAGE.DEALS;




